//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.02 at 09:34:26 PM EET 
//


package lab.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CandyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CandyType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Caramel"/&gt;
 *     &lt;enumeration value="Toffee"/&gt;
 *     &lt;enumeration value="Chocolate"/&gt;
 *     &lt;enumeration value="ChocolateWithFilling"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CandyType")
@XmlEnum
public enum CandyType {

    @XmlEnumValue("Caramel")
    CARAMEL("Caramel"),
    @XmlEnumValue("Toffee")
    TOFFEE("Toffee"),
    @XmlEnumValue("Chocolate")
    CHOCOLATE("Chocolate"),
    @XmlEnumValue("ChocolateWithFilling")
    CHOCOLATE_WITH_FILLING("ChocolateWithFilling");
    private final String value;

    CandyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CandyType fromValue(String v) {
        for (CandyType c: CandyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
