//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.02 at 09:34:26 PM EET 
//


package lab.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChocolateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChocolateType"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Dark"/&gt;
 *     &lt;enumeration value="Milk"/&gt;
 *     &lt;enumeration value="White"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "ChocolateType")
@XmlEnum
public enum ChocolateType {

    @XmlEnumValue("Dark")
    DARK("Dark"),
    @XmlEnumValue("Milk")
    MILK("Milk"),
    @XmlEnumValue("White")
    WHITE("White");
    private final String value;

    ChocolateType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChocolateType fromValue(String v) {
        for (ChocolateType c: ChocolateType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
