//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.02 at 09:34:26 PM EET 
//


package lab.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IngredientsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="IngredientsType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Water" type="{http://www.example.com/candies}PositiveInt"/&gt;
 *         &lt;element name="Sugar" type="{http://www.example.com/candies}PositiveInt"/&gt;
 *         &lt;element name="Fructose" type="{http://www.example.com/candies}PositiveInt"/&gt;
 *         &lt;element name="ChocolateType" type="{http://www.example.com/candies}ChocolateType" minOccurs="0"/&gt;
 *         &lt;element name="Vanillin" type="{http://www.example.com/candies}PositiveInt"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "IngredientsType", propOrder = {
    "water",
    "sugar",
    "fructose",
    "chocolateType",
    "vanillin"
})
public class IngredientsType {

    @XmlElement(name = "Water")
    protected int water;
    @XmlElement(name = "Sugar")
    protected int sugar;
    @XmlElement(name = "Fructose")
    protected int fructose;
    @XmlElement(name = "ChocolateType")
    @XmlSchemaType(name = "string")
    protected ChocolateType chocolateType;
    @XmlElement(name = "Vanillin")
    protected int vanillin;

    /**
     * Gets the value of the water property.
     * 
     */
    public int getWater() {
        return water;
    }

    /**
     * Sets the value of the water property.
     * 
     */
    public void setWater(int value) {
        this.water = value;
    }

    /**
     * Gets the value of the sugar property.
     * 
     */
    public int getSugar() {
        return sugar;
    }

    /**
     * Sets the value of the sugar property.
     * 
     */
    public void setSugar(int value) {
        this.sugar = value;
    }

    /**
     * Gets the value of the fructose property.
     * 
     */
    public int getFructose() {
        return fructose;
    }

    /**
     * Sets the value of the fructose property.
     * 
     */
    public void setFructose(int value) {
        this.fructose = value;
    }

    /**
     * Gets the value of the chocolateType property.
     * 
     * @return
     *     possible object is
     *     {@link ChocolateType }
     *     
     */
    public ChocolateType getChocolateType() {
        return chocolateType;
    }

    /**
     * Sets the value of the chocolateType property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChocolateType }
     *     
     */
    public void setChocolateType(ChocolateType value) {
        this.chocolateType = value;
    }

    /**
     * Gets the value of the vanillin property.
     * 
     */
    public int getVanillin() {
        return vanillin;
    }

    /**
     * Sets the value of the vanillin property.
     * 
     */
    public void setVanillin(int value) {
        this.vanillin = value;
    }

}
